<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PostSeeder extends Seeder
{
    private function px(int $id, int $w = 900, int $h = 500): string
    {
        return "https://images.pexels.com/photos/{$id}/pexels-photo-{$id}.jpeg?auto=compress&cs=tinysrgb&w={$w}&h={$h}&fit=crop";
    }

    public function run(): void
    {
        $admin = User::where('email', 'admin@indigenousbrands.zm')->first();

        $cat = fn($name) => Category::where('name', $name)->where('type', 'blog')->value('id');

        $posts = [

            // ── Lusaka Threads ──────────────────────────────────────────
            'Lusaka Threads' => [
                [
                    'title'          => 'How Chitenge Became a Global Fashion Statement',
                    'category'       => 'Zambian Culture',
                    'excerpt'        => 'Lusaka Threads designer Natasha Mwila shares how a fabric once reserved for ceremonies is now being seen on international runways.',
                    'featured_image' => $this->px(16863352),
                    'body'           => '<p>When Natasha Mwila founded Lusaka Threads in 2019, she had one simple goal: to prove that Zambian fashion could compete on the world stage without abandoning its roots. Five years later, her brand is stocked in boutiques from Johannesburg to London, and her chitenge-fused streetwear has appeared in three international magazines.</p><p>"Chitenge was always beautiful," Natasha explains. "It was used at funerals, at weddings, at celebrations. But nobody had really asked the question: what does chitenge look like on a twenty-five-year-old in Lusaka who listens to Afrobeats and watches fashion TikTok?" That question became the brand\'s founding philosophy.</p><p>The design process at Lusaka Threads starts with the fabric. Bolts of imported and locally-printed chitenge are laid out on long wooden tables, and the team — all of them Zambian, many from the same neighbourhood as Natasha — starts cutting. Every silhouette is developed from scratch, blending oversized hoodies with traditional wax-print panels, or pairing high-waisted trousers with embroidered chitenge detailing.</p><p>The international market noticed. A viral Instagram post in 2022 showing the brand\'s signature "Heritage Hoodie" generated over 400,000 impressions in 48 hours, leading to a sell-out of the entire first run within a week. Orders flooded in from the UK, the Netherlands, and Canada.</p><p>But Natasha is careful to keep the brand grounded. "We are not trying to be a Western brand that uses African print as a gimmick," she says firmly. "We are a Zambian brand. Full stop." That commitment shows in how the business is run: all sewing is done in Lusaka, all fabric sourcing prioritises local suppliers, and the brand actively mentors young Zambian fashion graduates.</p><p>As chitenge finds its place on global runways, Lusaka Threads remains the proof of concept that the future of African fashion is African — and it is very, very stylish.</p>',
                    'published_at'   => now()->subDays(30),
                ],
                [
                    'title'          => 'Behind the Stitch: A Day Inside the Lusaka Threads Workshop',
                    'category'       => 'Success Stories',
                    'excerpt'        => 'We spent a full day on the floor of Lusaka\'s most exciting fashion workshop and came away with a new appreciation for Zambian craftsmanship.',
                    'featured_image' => $this->px(12610340),
                    'body'           => '<p>The Lusaka Threads workshop sits in a converted warehouse in Woodlands, Lusaka. From the outside it is unremarkable — a corrugated iron roof, a hand-painted logo above the door. Inside, it is a completely different world: twenty sewing machines humming in synchrony, bolts of chitenge fabric stacked to the ceiling in every conceivable colour, and a team of tailors who move with the quiet confidence of people who are very good at what they do.</p><p>We arrived at seven in the morning, as the first shift was settling in. Head tailor Bwalya Tembo had already been there for an hour, checking the previous day\'s work against the brand\'s quality checklist. Each garment must pass twelve inspection points before it earns the Lusaka Threads label — a rigorous process that has earned the brand its reputation for quality.</p><p>"The customers know the difference," Bwalya says, holding up a half-finished jacket for inspection. "They buy from us because they know it was made properly. Not fast fashion. Proper fashion."</p><p>By nine o\'clock the workshop is in full swing. One team is cutting fabric using templates traced onto brown paper. Another is running pieces through industrial overlockers. A third group, the most senior tailors, handles the intricate hand-stitching details that make each garment unique. There is music playing — a mix of Zambian hip-hop and old-school Makossa — and a steady hum of conversation.</p><p>Founder Natasha Mwila stops by mid-morning to review a new sample for the upcoming winter collection. She holds it up against the light, turns it inside out to check the seams, then breaks into a wide smile. "This is the one," she says. The room brightens noticeably.</p><p>By the end of the day we had watched a jacket go from a bolt of fabric to a finished, labelled garment in under six hours. That pace, combined with the obvious pride everyone in the room takes in their work, is exactly why Lusaka Threads is not just a fashion brand — it is a movement.</p>',
                    'published_at'   => now()->subDays(18),
                ],
                [
                    'title'          => 'Dressing Zambia: The Cultural Politics of Indigenous Fashion',
                    'category'       => 'Entrepreneurship',
                    'excerpt'        => 'Why more Zambian designers are choosing to build local before going global — and what that means for the country\'s creative economy.',
                    'featured_image' => $this->px(1625775),
                    'body'           => '<p>There is a quiet revolution happening in Zambian fashion. Across the country, a new generation of designers is making a deliberate, principled choice: to build locally first, to source locally, to employ locally — and to let global success be a consequence of that commitment rather than the goal itself.</p><p>Lusaka Threads is perhaps the most visible example of this movement, but it is far from the only one. Across Lusaka, Livingstone, and the Copperbelt, young designers are opening small labels, building communities of loyal customers, and slowly, steadily, changing how Zambians think about fashion.</p><p>The economic dimension of this shift should not be underestimated. The fashion and textile sector in Zambia employs tens of thousands of people, from fabric printers and tailors to logistics workers and retailers. When customers choose local brands over imported fast fashion, that money stays in the country, circulates through local supply chains, and builds the kind of economic resilience that Zambia needs.</p><p>"Every time someone buys a Lusaka Threads hoodie instead of a hoodie from a Chinese fast-fashion platform, they are making an economic and a cultural statement," says Natasha Mwila. "They are saying: I value Zambian work. I value Zambian creativity. And that matters enormously."</p><p>The challenge, of course, is price. Local production costs more than offshore manufacturing. Zambian designers cannot compete on price with brands that pay workers pennies and externalise environmental costs. But they can compete — and increasingly are competing — on authenticity, quality, and story.</p><p>As global consumers grow more conscious about the origins of their clothing, the "made in Zambia" label is becoming a competitive advantage. The question now is whether Zambia\'s fashion ecosystem can scale up to meet the opportunity — and whether the government will support it with the investment and policy framework it deserves.</p>',
                    'published_at'   => now()->subDays(5),
                ],
            ],

            // ── Baobab Kitchen ──────────────────────────────────────────
            'Baobab Kitchen' => [
                [
                    'title'          => 'The Superfood in Your Backyard: Zambia\'s Baobab Revolution',
                    'category'       => 'Zambian Culture',
                    'excerpt'        => 'Long considered just a tree, the baobab is now at the centre of a thriving food export industry — and Zambian entrepreneurs are leading the charge.',
                    'featured_image' => $this->px(6190149),
                    'body'           => '<p>Across Zambia, the baobab tree has been a fixture of the landscape for millennia. Known locally as the "tree of life," it has provided shade, water, and food to generations of Zambians living in the bush. But until recently, it was rarely seen as a commercial opportunity. That is changing fast, and Baobab Kitchen is one of the companies driving the transformation.</p><p>Founded by food scientist Mwamba Kasonde, Baobab Kitchen has built a business around what she calls "the most nutritionally dense fruit most people have never heard of." Baobab powder — made from the dried pulp of the baobab fruit — contains six times more vitamin C than oranges, twice the calcium of milk, and more antioxidants than any other fruit on earth. It also has a naturally tangy, citrusy flavour that works beautifully in smoothies, baking, and sauces.</p><p>Mwamba spent two years testing recipes and refining her processing methods before launching commercially in 2020. Her breakthrough came when a UK-based health food distributor ordered 500 kilograms of baobab powder after seeing a post about the product on social media. "I had to call in favours from every farmer I knew to fill that order," she laughs. "But we filled it, and they came back for more."</p><p>Today, Baobab Kitchen sources from over 80 farmers across Zambia\'s Southern and Eastern provinces. The company pays above-market rates and provides training on sustainable harvesting techniques that protect the trees for future generations. It is a business model that is good for the farmers, good for the environment, and good for the company\'s supply chain reliability.</p><p>The baobab revolution is just getting started. As global demand for plant-based superfoods continues to grow, Zambia\'s baobab trees — millions of them, scattered across the bush — represent an extraordinary natural resource. Baobab Kitchen intends to make sure Zambian entrepreneurs are the ones who benefit from it.</p>',
                    'published_at'   => now()->subDays(28),
                ],
                [
                    'title'          => 'From Farm to Fork: Baobab Kitchen\'s Supply Chain Story',
                    'category'       => 'Sustainability',
                    'excerpt'        => 'How a Zambian food brand is building a fully traceable, farmer-first supply chain from bush to kitchen.',
                    'featured_image' => $this->px(3771120),
                    'body'           => '<p>When Mwamba Kasonde talks about supply chain, her eyes light up. For most food entrepreneurs, supply chain is a logistical headache. For Mwamba, it is the heart of what makes Baobab Kitchen different — and better.</p><p>Every product that leaves the Baobab Kitchen facility in Lusaka can be traced back to a specific farmer and a specific harvest. The company uses a simple but effective digital tracking system — built in-house by a Zambian software developer — that assigns a batch number to each delivery from the field. Customers who scan the QR code on their Baobab Kitchen packaging can see exactly which farming community their product came from, and a short profile of the farmers involved.</p><p>"Traceability is not just a marketing tool," Mwamba explains. "It is a quality control tool, an accountability tool, and a way of building relationships with our farmers. When they know their name is on the product, they care about quality in a different way."</p><p>The company works with farmer groups rather than individual smallholders, which makes logistics easier and ensures more consistent supply. Each group has a designated quality coordinator — usually a farmer elected by their peers — who does initial sorting and grading before the product is collected. This reduces the burden on Baobab Kitchen\'s processing team and gives the farmers themselves more stake in the quality of the end product.</p><p>The results speak for themselves. Baobab Kitchen\'s rejection rate — the proportion of raw material that fails quality testing on arrival — is under three percent, compared to an industry average of around twelve percent. That efficiency translates directly into better margins for both the company and its farming partners.</p><p>It is a model that other Zambian food brands are beginning to study and adapt. In an industry often characterised by opacity and exploitation, Baobab Kitchen is demonstrating that transparent, farmer-first supply chains are not just the ethical choice — they are the smart business choice too.</p>',
                    'published_at'   => now()->subDays(14),
                ],
                [
                    'title'          => 'Cooking with Zambia: 5 Indigenous Ingredients Changing African Food Culture',
                    'category'       => 'Zambian Culture',
                    'excerpt'        => 'From baobab to moringa, these Zambian pantry staples are moving from village kitchens to international restaurant menus.',
                    'featured_image' => $this->px(6097885),
                    'body'           => '<p>There is a quiet culinary revolution underway in Zambia, and its ingredients have been hiding in plain sight for generations. Across the country, food entrepreneurs, chefs, and brands like Baobab Kitchen are rediscovering and repackaging the incredible diversity of Zambia\'s indigenous food culture — and the world is paying attention.</p><p><strong>1. Baobab Powder</strong><br>The dried pulp of the baobab fruit is one of the world\'s most nutrient-dense foods, packed with vitamin C, fibre, and antioxidants. Its tangy, citrusy flavour makes it a natural fit for smoothies, energy bars, and baked goods. Baobab Kitchen has pioneered its commercial production in Zambia, and it is now appearing on health food shelves in Europe and North America.</p><p><strong>2. Moringa</strong><br>The moringa tree — called "the miracle tree" — grows abundantly across Zambia and produces leaves loaded with iron, calcium, and protein. Dried and ground into powder, moringa is used in teas, soups, and nutritional supplements. Several Zambian brands are now exporting moringa products to health-conscious markets globally.</p><p><strong>3. Wild Honey</strong><br>Zambia\'s forests produce some of the finest wild honey in Africa, harvested by traditional beekeepers using methods passed down through generations. Darker and more complex in flavour than commercial honey, Zambian wild honey is prized by chefs and foodies for its depth and character.</p><p><strong>4. Groundnuts</strong><br>A cornerstone of Zambian cooking, groundnuts appear in everything from nshima accompaniments to street food snacks. Cold-pressed Zambian groundnut oil is gaining recognition as a premium cooking oil with a distinctly rich flavour profile.</p><p><strong>5. Dried Kapenta</strong><br>These tiny dried fish from Lake Tanganyika and Lake Kariba are a protein powerhouse and a staple of the Zambian diet. Increasingly, innovative food brands are finding ways to incorporate kapenta into snacks, seasonings, and even premium restaurant dishes.</p><p>The food revolution starts in the kitchen, and Zambia\'s kitchen is stocked with extraordinary ingredients. The brands that learn to tell their story — like Baobab Kitchen is doing — will be the ones that carry Zambian food culture to the world.</p>',
                    'published_at'   => now()->subDays(6),
                ],
            ],

            // ── Copper Art Studio ───────────────────────────────────────
            'Copper Art Studio' => [
                [
                    'title'          => 'Mining Heritage, Making Art: The Story of Copper Art Studio',
                    'category'       => 'Success Stories',
                    'excerpt'        => 'A Ndola collective is turning the Copperbelt\'s industrial past into breathtaking sculpture — and changing lives in the process.',
                    'featured_image' => $this->px(29630131),
                    'body'           => '<p>The Copperbelt has always been defined by what lies beneath the earth. For most of the twentieth century, that meant extraction — copper ore pulled from the ground and shipped away, leaving behind both prosperity and, eventually, the scars of a boom-and-bust economy. Copper Art Studio is doing something different: it is taking that same material and turning it into something that endures, that speaks, that moves people.</p><p>Founded in Ndola by sculptor and community activist Joseph Ng\'uni, the studio began as a small workshop in 2018 with two employees and a handful of tools. Today it employs fifteen people and produces sculptural pieces that have been exhibited in Johannesburg, Nairobi, and Cape Town. But the commercial success is almost secondary to what the studio represents in the community it serves.</p><p>"We started this because there were young people in Ndola with incredible talent and no outlet," Joseph explains. "The mines were not hiring. The formal economy had nothing for them. But they had their hands and their imagination — and that turned out to be enough."</p><p>The process is labour-intensive and deeply skilled. Sheets and offcuts of copper — sourced from local recyclers and occasionally donated by mining companies — are cut, beaten, welded, and polished into forms that range from abstract geometric pieces to figurative works depicting scenes from Copperbelt life: miners, market women, children playing in the streets.</p><p>Each piece takes between two days and two weeks to complete, depending on its complexity. The studio does not rush. "Copper does not lie," Joseph says. "Every mark you make on it stays. So you have to be intentional, you have to be patient, and you have to believe in what you are making."</p><p>That philosophy — of craft as a form of truth-telling, of art as a form of community — has made Copper Art Studio one of the most respected creative enterprises on the Copperbelt. And as the Zambian art market grows, it is making a compelling case that the region\'s creative economy can be just as valuable as its mineral one.</p>',
                    'published_at'   => now()->subDays(25),
                ],
                [
                    'title'          => 'Youth, Art, and the Future of Zambia\'s Creative Economy',
                    'category'       => 'Innovation',
                    'excerpt'        => 'How free art programmes in the Copperbelt are giving young Zambians a path out of unemployment and into creative enterprise.',
                    'featured_image' => $this->px(17931802),
                    'body'           => '<p>Every Saturday morning, fifteen to twenty young people gather at the Copper Art Studio in Ndola for what the studio calls its Open Workshop. There are no fees, no formal entry requirements, no age limit — just tools, materials, and experienced craftspeople willing to teach.</p><p>The programme began informally in 2019, when Joseph Ng\'uni started inviting neighbourhood kids to come and watch the artisans at work. A few started asking questions. A few more asked if they could try. Within months, the Saturday sessions had become the most anticipated event in the local creative calendar.</p><p>Today, the Open Workshop has a waiting list. Over three years, it has trained more than 200 young people in metalworking, sculpture, and design thinking. A handful have gone on to formal arts education. Several are now employed at the studio itself. Others have used the skills they learned to set up their own small creative businesses.</p><p>The economic impact of creative education programmes like this is difficult to quantify but impossible to ignore. Zambia has one of the youngest populations in the world — the median age is under eighteen — and creating viable economic pathways for young people is one of the country\'s most pressing challenges. The creative economy is not a silver bullet, but it is a significant and underinvested opportunity.</p><p>"We are not just teaching people to make art," Joseph says. "We are teaching people to see problems as creative opportunities. To use their hands. To be patient and disciplined. To take pride in making something well. Those are not just artistic skills — they are life skills, and they are entrepreneurial skills."</p><p>As Zambia\'s creative sector grows and begins to attract international attention, programmes like the Copper Art Studio Open Workshop are the grassroots infrastructure that makes it all possible. They deserve far more recognition — and far more public investment — than they currently receive.</p>',
                    'published_at'   => now()->subDays(11),
                ],
                [
                    'title'          => 'The Art of Recycling: Copper Art Studio\'s Sustainability Story',
                    'category'       => 'Sustainability',
                    'excerpt'        => 'How one Zambian studio turned industrial waste into gallery-worthy sculpture — and built a sustainable business model in the process.',
                    'featured_image' => $this->px(4560092),
                    'body'           => '<p>In most industries, scrap metal is a problem to be managed. At Copper Art Studio, it is the raw material for everything. The studio sources almost all of its copper from local recyclers, scrap dealers, and — increasingly — direct donations from mining operations looking to responsibly dispose of offcuts and surplus material. It is a supply chain model that is both economical and environmental, and it is central to what makes the studio\'s work so meaningful.</p><p>"There is something powerful about the idea that material which was headed for a landfill ends up as a piece of art in someone\'s home or gallery," says founder Joseph Ng\'uni. "The transformation is not just aesthetic. It is a statement about value — about what we choose to treat as worthless and what we choose to treat as precious."</p><p>The studio has formalised this philosophy into what it calls its Circular Craft Model. Under this model, the studio tracks the origin of every piece of copper it uses and documents the journey from raw material to finished artwork. This documentation becomes part of the story told to buyers and galleries — an artistic provenance that adds both meaning and commercial value to each piece.</p><p>The model has also opened up unexpected partnerships. Three major copper mining companies now donate surplus material to the studio in exchange for a small number of commissioned pieces for their corporate offices. It is an arrangement that costs the companies little but earns the studio both materials and visibility.</p><p>As circular economy principles move from niche to mainstream in global business thinking, Copper Art Studio finds itself ahead of the curve — not because it was thinking about trends, but because sustainability was baked into the studio\'s DNA from the very beginning. That authenticity, more than any marketing strategy, is what resonates with the galleries and collectors who have made the studio\'s work internationally sought-after.</p>',
                    'published_at'   => now()->subDays(3),
                ],
            ],

            // ── Ngozi Beauty ────────────────────────────────────────────
            'Ngozi Beauty' => [
                [
                    'title'          => 'Science Meets Tradition: Inside Ngozi Beauty\'s Lab',
                    'category'       => 'Innovation',
                    'excerpt'        => 'Dr. Chanda Phiri explains how she combines cutting-edge biochemistry with centuries-old African botanical knowledge to create her award-winning skincare range.',
                    'featured_image' => $this->px(11440539),
                    'body'           => '<p>Most skincare brands choose between science and nature. Ngozi Beauty refuses to. Founded by biochemist Dr. Chanda Phiri, the brand has built its entire product philosophy around the premise that the most effective skincare draws equally on rigorous scientific research and deep traditional botanical knowledge — and that these two sources of wisdom are more complementary than they are contradictory.</p><p>"When I look at an ingredient like marula oil, I see it through two lenses simultaneously," Dr. Phiri explains, gesturing at the rows of amber bottles lining the shelves of her Lusaka laboratory. "I see it as a biochemist — I know its fatty acid composition, its antioxidant activity, its penetration rate through the skin barrier. But I also see it through the lens of the communities that have been using it for generations, who knew empirically that it worked even before anyone could explain why."</p><p>That dual perspective is what makes Ngozi Beauty\'s formulations unusually effective. The brand\'s flagship moisturiser, the Marula Glow Cream, combines marula oil with baobab extract and a patented encapsulation technology that delivers active ingredients to the deepest layers of the epidermis. It took Dr. Phiri eighteen months and over 200 formulation iterations to get it right — but it now has a waiting list of several thousand customers across Africa and Europe.</p><p>The laboratory itself is compact but immaculate — a converted room in a commercial building in Lusaka\'s Kabulonga neighbourhood. Dr. Phiri employs two lab technicians and a quality assurance manager, all of them Zambian, all of them trained partly in-house. Every batch of every product is tested for stability, microbial safety, and efficacy before it leaves the building.</p><p>"Zambian skin deserves Zambian science," Dr. Phiri says simply. "For too long, African consumers have been told that the best skincare comes from European or American labs. We are disproving that, one product at a time."</p>',
                    'published_at'   => now()->subDays(22),
                ],
                [
                    'title'          => 'Why African Skincare is Finally Getting the Recognition It Deserves',
                    'category'       => 'Entrepreneurship',
                    'excerpt'        => 'A new wave of African beauty brands is challenging global skincare giants — and winning. Here\'s why.',
                    'featured_image' => $this->px(8689920),
                    'body'           => '<p>For decades, the global skincare industry told African consumers a damaging story: that their skin was a problem to be solved, and that the solutions came from abroad. Skin-lightening creams, formulations designed for European skin types, marketing that equated beauty with lightness — the legacy of this narrative is still felt across the continent. But something is shifting, and it is shifting fast.</p><p>A new generation of African beauty entrepreneurs — scientists, formulators, marketers, and visionaries — is building brands that start from a radically different premise: that African skin is not a problem, it is an opportunity. That the ingredients growing in African soil are not second-best alternatives to imported actives, they are often superior. And that African consumers deserve products built for them, tested on them, and priced for them.</p><p>Ngozi Beauty\'s Dr. Chanda Phiri is one of the leaders of this movement. Her brand has grown to over 50,000 customers across sub-Saharan Africa in under four years, almost entirely through word of mouth and social media. She has never spent a significant amount on traditional advertising. She has not needed to — because her products work, and her customers tell their friends.</p><p>"The global beauty industry underestimated African consumers," she says. "They assumed we would keep buying whatever was imported and marketed at us. But African women are sophisticated, informed, and increasingly connected. They can research ingredients. They can compare formulations. They can choose."</p><p>The commercial opportunity is enormous. Africa is home to over 1.4 billion people, with a growing middle class and a rising appetite for premium, locally-relevant products. Analysts estimate that the African beauty market will be worth over $12 billion by 2030. The question is whether that value accrues to African entrepreneurs — or to global corporations that parachute in with "African-inspired" products made elsewhere.</p><p>Brands like Ngozi Beauty are making the case, decisively, for the former.</p>',
                    'published_at'   => now()->subDays(9),
                ],
                [
                    'title'          => 'From Zambia\'s Forests to Your Bathroom Shelf: The Story of Marula Oil',
                    'category'       => 'Zambian Culture',
                    'excerpt'        => 'One of skincare\'s hottest ingredients has been a Zambian secret for centuries. We trace its journey from tree to bottle.',
                    'featured_image' => $this->px(33968170),
                    'body'           => '<p>Walk through the miombo woodlands of southern Zambia in late summer and you will find the marula trees heavy with fruit — small, yellow-green, and smelling faintly of turpentine when unripe, then sweet and citrusy as they fall. Elephants travel for miles to eat them. Women have pressed oil from their kernels for generations. And now, increasingly, the world\'s most discerning skincare consumers are seeking them out.</p><p>Marula oil is one of the most effective natural skincare ingredients known to science. Its fatty acid profile — dominated by oleic acid, with significant amounts of linoleic acid and a remarkable range of minor actives — makes it exceptionally moisturising, rapidly absorbed, and highly stable against oxidation. In plain terms: it goes on your skin, soaks in immediately without greasiness, and keeps working for hours.</p><p>But for the women of Zambia\'s southern and western provinces, this was never news. Marula oil has been used as a skin moisturiser, a hair conditioner, and a cooking oil for centuries. The knowledge of how to crack the hard inner kernel, press the oil, and store it without it going rancid was passed down through generations of women — practical, embodied, and entirely unpublished.</p><p>Ngozi Beauty\'s Dr. Chanda Phiri grew up watching her grandmother use marula oil. When she went to university to study biochemistry, she began to understand, in scientific terms, why it worked. When she founded her skincare brand, marula oil was the obvious centrepiece.</p><p>But Dr. Phiri was also determined to ensure that the communities who had always known about marula oil would benefit from its commercial success. The brand works with a women\'s cooperative in Southern Province, paying above-market prices for hand-pressed marula oil and providing the cooperative with business training and cold-storage equipment to improve their product quality and shelf life.</p><p>"This ingredient belongs to these communities," Dr. Phiri says simply. "We are just helping it find a wider audience."</p>',
                    'published_at'   => now()->subDays(2),
                ],
            ],

            // ── ZedTech Solutions ────────────────────────────────────────
            'ZedTech Solutions' => [
                [
                    'title'          => 'ZedPay: Building a Mobile Payment Revolution in Zambia',
                    'category'       => 'Innovation',
                    'excerpt'        => 'How a Lusaka startup processed two million transactions in a single month — and why that matters for Zambia\'s financial inclusion story.',
                    'featured_image' => $this->px(5792871),
                    'body'           => '<p>Three years ago, paying for goods and services in Zambia\'s informal economy meant cash — only cash, always cash, and the friction, risk, and exclusion that came with it. For the millions of Zambians who ran small businesses or worked outside the formal banking sector, digital payments were something that happened to other people in other countries.</p><p>ZedTech Solutions is changing that. Their flagship product, ZedPay, is a mobile payment platform designed specifically for the Zambian market — built around the realities of intermittent internet connectivity, feature phones as well as smartphones, and a customer base that ranges from university students to rural market traders.</p><p>"We did not copy a Silicon Valley payments product and try to make it work in Zambia," says ZedTech co-founder and CEO Mwangi Banda. "We started from scratch. We went to markets, we talked to traders, we understood what they needed. And then we built that."</p><p>What they built is deceptively simple on the surface: a USSD-based payment system that works on any phone with any network, with a smartphone app for users who want more features, and a merchant dashboard that even first-time tech users can navigate in under five minutes. Behind the scenes, the infrastructure is considerably more sophisticated — built to handle high transaction volumes with minimal downtime and to meet the Bank of Zambia\'s regulatory requirements for digital financial services.</p><p>The numbers tell a compelling story. ZedPay now processes over two million transactions monthly, handling everything from utility bill payments to school fees to market purchases. Over 300 small businesses use the merchant platform, and the company has partnered with two microfinance institutions to offer ZedPay users access to small loans based on their transaction history.</p><p>For Mwangi, the goal was always financial inclusion. "Payments are the entry point," he explains. "Once someone has a digital payment history, they become visible to the financial system. They can access credit. They can save. They can build a financial life. That is transformational."</p>',
                    'published_at'   => now()->subDays(27),
                ],
                [
                    'title'          => 'Code for Zambia: How ZedTech\'s Bootcamp Is Building the Next Generation',
                    'category'       => 'Entrepreneurship',
                    'excerpt'        => '400 young Zambians trained, dozens of jobs created, and a growing pipeline of local tech talent. Inside the bootcamp changing the country\'s digital future.',
                    'featured_image' => $this->px(3799124),
                    'body'           => '<p>In a bright, air-conditioned room in Lusaka\'s Northmead neighbourhood, thirty young Zambians are staring intently at laptops. Some are writing their first lines of Python. Others are debugging mobile app prototypes. A few, in the advanced cohort, are building APIs that would not look out of place in a San Francisco startup. They are all students at the ZedTech Coding Bootcamp — and they are all, in varying ways, rewriting their futures.</p><p>ZedTech Solutions launched the bootcamp in 2021 as a response to a problem the company encountered in its own hiring process: there simply were not enough trained Zambian software developers to fill the roles the growing tech sector needed. The bootcamp was the company\'s attempt to fix that at the source — to invest in creating the talent pipeline that Zambia\'s digital economy needed.</p><p>The programme runs in cohorts of 25-30 students, over sixteen weeks, covering web development, mobile development, and data fundamentals. It is free for students who are accepted through a competitive application process. Operating costs are covered partly by ZedTech itself and partly by a growing number of corporate sponsors who have recognised that the bootcamp is building their future workforce.</p><p>"We are not a charity," CEO Mwangi Banda is clear. "We are making a strategic investment. Every good developer we train is a potential hire for us or for the broader ecosystem. If the Zambian tech sector grows, ZedTech grows."</p><p>Over three years, more than 400 students have completed the programme. The employment rate among graduates is over 70% within six months of completion — extraordinary by any standard. A number have gone on to found their own tech startups. Several work at ZedTech itself.</p><p>Perhaps most significantly, over 40% of bootcamp graduates are women — a proportion that reflects ZedTech\'s deliberate effort to recruit from communities that have historically been excluded from technology careers. In an industry notorious for gender imbalance, that number is remarkable.</p>',
                    'published_at'   => now()->subDays(16),
                ],
                [
                    'title'          => 'Agritech in Zambia: How Technology is Transforming the Farm',
                    'category'       => 'Innovation',
                    'excerpt'        => 'From SMS crop price alerts to satellite-based yield prediction, Zambian agritech is quietly revolutionising how the country grows food.',
                    'featured_image' => $this->px(30678211),
                    'body'           => '<p>Zambia\'s economy is built on agriculture. Over 60% of the population depends on farming for their livelihoods, and the sector accounts for a significant share of GDP. Yet for most of that history, Zambian farmers have operated with remarkably little information — uncertain about prices, cut off from markets, and unable to access the credit or inputs they need to be productive.</p><p>Technology is changing that, and Zambian entrepreneurs are at the forefront of the change. ZedTech Solutions — better known for its ZedPay mobile payment platform — has quietly built one of the most sophisticated agritech tools in the region: a platform called FarmConnect that links smallholder farmers to real-time crop prices, weather data, input suppliers, and buyers.</p><p>FarmConnect works on any phone via SMS, making it accessible to the millions of Zambian farmers who do not have smartphones or reliable internet access. Farmers register their crops and locations, and the system sends daily price alerts for the markets nearest to them, weather forecasts for their specific area, and periodic advice on planting and pest management calibrated to their reported crop types.</p><p>The impact on farmer income has been measurable. In a pilot programme in Eastern Province, participating farmers achieved prices on average 18% higher than non-participating farmers selling the same crops at the same time — simply because they had information about where prices were highest and when to sell.</p><p>"Information is power," says ZedTech CEO Mwangi Banda. "Zambian farmers are not poor because they are unproductive. They are poor partly because they have been systematically cut off from the information they need to make good decisions. We are trying to fix that."</p><p>FarmConnect has now reached over 15,000 farmers across five provinces. ZedTech plans to expand to all ten provinces within two years. It is one of the most tangible demonstrations yet that technology built in Zambia, for Zambia, can change Zambian lives.</p>',
                    'published_at'   => now()->subDays(4),
                ],
            ],

            // ── Chitenge Collective ──────────────────────────────────────
            'Chitenge Collective' => [
                [
                    'title'          => 'Twelve Designers, One Vision: The Story of the Chitenge Collective',
                    'category'       => 'Entrepreneurship',
                    'excerpt'        => 'How a group of independent Zambian designers came together under one umbrella — and why the model is working.',
                    'featured_image' => $this->px(12610340),
                    'body'           => '<p>In the fashion industry, strength is usually assumed to come from scale — from a single brand large enough to negotiate manufacturing contracts, afford advertising campaigns, and command shelf space in major retailers. The Chitenge Collective is testing a different hypothesis: that the strength of twelve independent designers, pooled and coordinated, can achieve what none of them could manage alone.</p><p>Founded in Livingstone in 2020, the Collective brings together twelve independent Zambian designers under a shared brand, shared logistics, and shared values. Each designer retains full creative independence — their name appears on their pieces, their aesthetic remains their own. But they share a production facility, a marketing budget, a website, and a logistics operation that can ship globally. They also share the Chitenge Collective name, which has become, over four years, significantly more powerful than any individual designer\'s personal brand.</p><p>The idea came from coordinator Thandiwe Moyo, a Livingstone-born fashion entrepreneur who had spent a decade watching talented Zambian designers fail not because their work was not good enough, but because they could not afford the infrastructure that good work alone does not provide.</p><p>"Talent is everywhere in Zambia," Thandiwe says. "What is scarce is capital, logistics, and market access. So I thought: what if we shared those things? What if we built the infrastructure collectively and then invited the best designers to use it?"</p><p>The results have exceeded even Thandiwe\'s optimistic projections. In their first year, the Collective achieved combined sales of ZMW 2.3 million. By year three, that had grown to over ZMW 9 million. Individual designers have seen their personal income grow by an average of 340% since joining. And the Chitenge Collective name has appeared in Vogue Africa, been worn by celebrities at international events, and generated partnership enquiries from retailers in six countries.</p><p>It is a model with profound implications — not just for fashion, but for any creative sector where individual talent is abundant but shared infrastructure is scarce.</p>',
                    'published_at'   => now()->subDays(24),
                ],
                [
                    'title'          => 'Chitenge Fabric: The Living Archive of Zambian Identity',
                    'category'       => 'Zambian Culture',
                    'excerpt'        => 'More than a textile, chitenge is a language — and Zambian designers are becoming its most eloquent speakers.',
                    'featured_image' => $this->px(11403818),
                    'body'           => '<p>Chitenge — the brightly printed cotton fabric worn across sub-Saharan Africa — is many things simultaneously. It is functional, practical, and affordable. It is celebratory, ceremonial, and deeply personal. It is simultaneously ancient in its cultural associations and remarkably contemporary in its visual energy. And in the hands of designers like those who make up the Chitenge Collective, it is becoming a medium for one of the most exciting artistic conversations happening anywhere in the world.</p><p>The fabric itself has a complex history. Most chitenge used in Zambia is manufactured in West Africa, South Asia, or the Netherlands — a quirk of colonial trade patterns that saw European manufacturers develop wax-print fabrics for African markets in the nineteenth century. But despite its production origins, chitenge has been entirely claimed by the communities that wear it. The patterns have local meanings. The way it is worn communicates social status, occasion, and identity. It has become, over generations, deeply Zambian.</p><p>The Chitenge Collective\'s designers engage with this complexity thoughtfully. Some work with traditional patterns, adapting them for contemporary silhouettes while preserving their original meanings. Others commission entirely new patterns from visual artists, creating prints that speak to contemporary Zambian life — urban architecture, wildlife, political moments, social media culture.</p><p>"Chitenge is not a static thing," says Collective coordinator Thandiwe Moyo. "It has always changed, always evolved, always absorbed new influences. What we are doing is part of that continuous evolution. We are not guardians of a museum — we are participants in a living tradition."</p><p>That living tradition is finding new audiences worldwide. The Collective\'s capsule collections sell out within days of launch, driven by a global community of African diaspora customers and non-African consumers who have connected with the fabric\'s visual power and cultural richness. Chitenge is no longer just a Zambian story — it is becoming a global one.</p>',
                    'published_at'   => now()->subDays(12),
                ],
                [
                    'title'          => 'Giving Back Through Fashion: The Collective\'s Women\'s Cooperative',
                    'category'       => 'Sustainability',
                    'excerpt'        => 'Ten percent of every Chitenge Collective sale goes to women\'s tailoring cooperatives in rural Zambia. Here\'s what that money does.',
                    'featured_image' => $this->px(4910234),
                    'body'           => '<p>From the beginning, the Chitenge Collective built social impact into its financial model rather than treating it as an afterthought. Ten percent of all sales — not profit, sales — goes directly to a fund that supports women\'s tailoring cooperatives in rural Zambia. In the three years since the model was established, that fund has distributed over ZMW 900,000 to cooperatives in six provinces.</p><p>The cooperatives that benefit from the fund are not passive recipients. They are selected through a competitive application process, assessed on their governance structures, their training programmes, and their economic impact in their communities. Fund recipients receive not just money but ongoing support — business mentoring, access to the Collective\'s fabric suppliers, and opportunities to produce pieces for the Collective\'s mainstream range.</p><p>In Kabwe, one cooperative has used fund support to purchase five industrial sewing machines, upgrade their workspace, and train twelve new members. Their income has increased by over 200% since receiving support, and they now produce a small capsule of products sold under their own label through the Collective\'s website.</p><p>In Chipata, a cooperative of twenty women has used funding to establish a training programme for school leavers, providing six-month placements that teach garment construction, pattern-making, and basic business management. Thirty-eight young women have completed the programme and gone on to employment or self-employment in the garment sector.</p><p>"We wanted a model where commercial success and social impact were the same thing," says coordinator Thandiwe Moyo. "When the Collective does well, the cooperatives do well. That alignment is not incidental — it is the whole point."</p><p>As impact investing and purpose-led business models become increasingly mainstream, the Chitenge Collective offers a template that is both commercially robust and genuinely transformative. It is proof that fashion can be a force for good — when its architects choose to make it so.</p>',
                    'published_at'   => now()->subDays(1),
                ],
            ],

            // ── Victoria Jewels ──────────────────────────────────────────
            'Victoria Jewels' => [
                [
                    'title'          => 'Zambia\'s Hidden Gems: The World-Class Gemstones Beneath Our Feet',
                    'category'       => 'Zambian Culture',
                    'excerpt'        => 'Zambia produces some of the world\'s finest emeralds, amethysts, and malachite — but the value has rarely stayed in the country. Victoria Jewels is changing that.',
                    'featured_image' => $this->px(2360530),
                    'body'           => '<p>Zambia is one of the world\'s most significant gemstone producers. The country\'s emeralds — mined primarily in the Copperbelt and Northwestern provinces — are considered among the finest on earth, prized for their deep green colour and remarkable clarity. Zambian amethyst is world-renowned. The malachite deposits of the Copperbelt produce material of extraordinary quality, used in jewellery and decorative art worldwide.</p><p>And yet, for most of Zambia\'s history as a gemstone producer, the value created by these extraordinary materials has not stayed in the country. Rough stones have been exported, cut and polished elsewhere, set into jewellery by craftspeople in other countries, and sold to consumers who may never have heard of Zambia. The country has been a source, not a destination.</p><p>Victoria Jewels is part of a growing effort to change that equation. Founded by goldsmith Mulenga Kapasa in Livingstone, the brand designs, produces, and sells fine jewellery using Zambian gemstones set by Zambian craftspeople — keeping as much of the value chain as possible within the country.</p><p>"When you buy a Victoria Jewels piece, you are buying something that was dug up in Zambia, cut in Zambia, designed in Zambia, and made in Zambia," Mulenga says. "Every part of that process creates Zambian jobs and builds Zambian skills. That is what value addition looks like."</p><p>The business case is compelling. A rough emerald sold at the mine gate might fetch $50. The same stone, cut, set, and sold as part of a fine jewellery piece, might command $500 or more. That differential — multiplied across thousands of pieces — represents an enormous economic opportunity that Zambia has historically exported along with its stones.</p><p>Victoria Jewels has won three Pan-African Design Awards and ships to collectors in 18 countries. The brand is small by global standards, but it is proof of concept for an industry that could be transformative for Zambia\'s economy.</p>',
                    'published_at'   => now()->subDays(26),
                ],
                [
                    'title'          => 'Ethical Gemstones: Why Provenance Is the New Luxury',
                    'category'       => 'Sustainability',
                    'excerpt'        => 'Jewellery consumers are demanding to know where their stones come from. Victoria Jewels has always been ready to tell them.',
                    'featured_image' => $this->px(28521274),
                    'body'           => '<p>In the global luxury jewellery market, provenance has become the new hallmark of value. Informed consumers — particularly younger buyers in North America, Europe, and Asia — are increasingly unwilling to purchase gemstones without knowing where they came from, who mined them, and whether the mining was conducted responsibly. The era of "conflict diamonds" brought this issue to global attention, and the conversation has since expanded to cover emeralds, rubies, sapphires, and coloured stones broadly.</p><p>Victoria Jewels has been ahead of this curve since day one. Every gemstone used by the brand is sourced directly from licensed Zambian miners, with full documentation of origin, chain of custody, and licensing status. The brand works with a network of trusted small-scale miners who have committed to responsible extraction practices in exchange for preferential pricing and a stable commercial relationship.</p><p>"We know every stone we use," says founder Mulenga Kapasa. "We know which mine it came from, we know who cut it, and we can tell that story to the customer. In the luxury market, that story is part of what they are paying for."</p><p>The commercial impact of this commitment to transparency has been significant. Victoria Jewels commands price premiums over comparable pieces from brands without certified ethical sourcing — and its customers pay those premiums willingly. In a customer survey conducted last year, 94% of respondents said that knowing the provenance of their Victoria Jewels piece was "important" or "very important" to their decision to buy.</p><p>The brand is also beginning to see interest from luxury retailers who are seeking ethically-sourced African gemstones for their own collections. Three premium European jewellery houses have approached Victoria Jewels about potential wholesale partnerships. For Mulenga, this interest validates the company\'s approach — and represents a significant potential growth pathway.</p><p>"Ethical sourcing is not a constraint on our business," she says. "It is our competitive advantage. And I believe it will become the standard for the entire industry within a decade."</p>',
                    'published_at'   => now()->subDays(13),
                ],
                [
                    'title'          => 'Crafting Zambia\'s Story: An Interview with Goldsmith Mulenga Kapasa',
                    'category'       => 'Success Stories',
                    'excerpt'        => 'The award-winning jeweller behind Victoria Jewels talks craft, identity, and why she chose to build in Zambia instead of moving abroad.',
                    'featured_image' => $this->px(1625775),
                    'body'           => '<p>Mulenga Kapasa learned to work with metal in her uncle\'s garage in Livingstone. He repaired cars for a living, but on weekends, when the clients had gone, he made things for pleasure — small sculptures, decorative objects, pieces of jewellery for family members. Mulenga watched him, then started helping, then started making things of her own.</p><p>"I understood very early that metal had a kind of memory," she says. "When you work it — when you heat it and beat it and form it — it remembers what you did. Every mark you leave is permanent. That made me take it very seriously."</p><p>She took it seriously enough to pursue formal training, eventually studying goldsmithing and jewellery design in South Africa before returning to Zambia to found Victoria Jewels. The decision to come back was not obvious. Several of her contemporaries stayed in South Africa or moved to Europe. The opportunities were larger, the markets more developed, the infrastructure more reliable.</p><p>"I thought about it," she admits. "Seriously. But I kept coming back to one question: what do I actually want to build? And the answer was always: something Zambian. Something that tells a Zambian story. And you cannot do that from somewhere else."</p><p>The early years were hard. Access to capital was limited. The local market for fine jewellery was small. Sourcing consistent quality gemstones required building relationships that took years to establish. There were months when the business barely survived.</p><p>But Mulenga kept making. She kept entering competitions, kept showing at exhibitions, kept telling her story. The Pan-African Design Awards brought visibility. A profile in an international trade publication brought wholesale enquiries. A partnership with a Nairobi gallery brought a new market. Slowly, then more quickly, the business built momentum.</p><p>Today, Victoria Jewels ships to collectors in 18 countries and has a waiting list for its most sought-after pieces. Mulenga employs four full-time craftspeople and two part-time gemstone cutters — all of them Zambian. She is training the next generation of Zambian jewellers, because she knows that the industry she is building needs more than one brand to sustain it.</p><p>"I did not come back to Zambia to build a small business," she says, with a smile that carries both warmth and steel. "I came back to build an industry."</p>',
                    'published_at'   => now()->subDays(7),
                ],
            ],

            // ── Savanna Brew Co ──────────────────────────────────────────
            'Savanna Brew Co' => [
                [
                    'title'          => 'Craft Beer with a Zambian Soul: Inside the Savanna Taproom',
                    'category'       => 'Entrepreneurship',
                    'excerpt'        => 'Zambia\'s first independent craft brewery is more than a beer brand — it is a community hub, a local supply chain, and a statement about what Zambian entrepreneurship can achieve.',
                    'featured_image' => $this->px(6097885),
                    'body'           => '<p>On a Friday evening, the Savanna Brew Co taproom in Lusaka is alive. Tables are packed, the long bar is three people deep, and from the brewing area behind the serving counter comes the warm, yeasty smell of fermentation in progress. It feels like a place that has been here forever — comfortable, convivial, deeply local — even though it only opened its doors three years ago.</p><p>That sense of rootedness is exactly what founder Chileshe Mwape was aiming for. When he conceived Savanna Brew Co, he was not just thinking about beer. He was thinking about community — about creating a space where Lusaka\'s creative and entrepreneurial class could gather, collaborate, and feel at home. The beer, he decided, would be the vehicle for that vision.</p><p>"In most cities, craft breweries become community anchors," Chileshe explains, surveying the packed room with evident satisfaction. "They are the place where people meet, where ideas happen, where the city\'s energy concentrates. I wanted Lusaka to have that."</p><p>What makes Savanna Brew Co distinctive, beyond the quality of its beer, is its commitment to Zambian ingredients. The brewery\'s flagship lager is brewed with sorghum sourced from smallholder farmers in Eastern Province. The seasonal Baobab Wheat Ale — which sells out within days of each batch release — uses baobab fruit from Southern Province. The winter Honey Stout features wild honey from a beekeeping cooperative in the Kafue flats.</p><p>These are not marketing gimmicks. They represent real supply chain relationships that Chileshe has built over three years of visiting farms, attending harvest festivals, and sometimes personally driving produce back to the brewery. They also mean that every beer sold at Savanna Brew Co sends money into Zambian agriculture — a fact that Chileshe communicates clearly to every customer who asks about the menu.</p><p>"I want people to taste where this comes from," he says, sliding a glass of the amber Baobab Wheat across the bar. "I want them to taste Zambia."</p>',
                    'published_at'   => now()->subDays(20),
                ],
                [
                    'title'          => 'The Rise of Zambia\'s Craft Beverage Scene',
                    'category'       => 'Entrepreneurship',
                    'excerpt'        => 'From craft beer to botanical spirits to specialty coffee, a new generation of Zambian beverage entrepreneurs is building something remarkable.',
                    'featured_image' => $this->px(3771120),
                    'body'           => '<p>Five years ago, the answer to "what is the Zambian craft beverage scene?" would have been a short one. Today, it is a different conversation entirely. Across Lusaka, Ndola, Livingstone, and increasingly in smaller towns, a new generation of entrepreneurs is building beverage brands that are proudly local, technically sophisticated, and commercially ambitious.</p><p>Savanna Brew Co is perhaps the most visible example, but it is far from alone. A craft gin distillery in Lusaka\'s Woodlands neighbourhood is producing small-batch botanical spirits using indigenous Zambian plants — including moringa, baobab, and wild rosemary — that have garnered attention from spirits enthusiasts as far afield as the UK. A specialty coffee roastery is sourcing beans from Zambia\'s emerging coffee-growing regions in Northern Province and roasting them to standards that would not be out of place in Melbourne or Portland. A kombucha producer is fermenting locally with Zambian tea blends and fruit, building a fast-growing base of health-conscious consumers.</p><p>"What is happening is a kind of collective realisation," says Chileshe Mwape of Savanna Brew Co. "People are realising that the best ingredients are often right here. That the most interesting flavour stories are Zambian stories. And that there is a market — locally and internationally — for products that tell those stories with authenticity and quality."</p><p>The economic logic is compelling. The global craft beverage market is growing rapidly, driven by consumers seeking authentic, small-batch products with traceable ingredients and compelling stories. Zambia, with its extraordinary array of indigenous botanicals, fruits, and agricultural products, is extraordinarily well positioned to compete in this market — if it can develop the brands, the production infrastructure, and the marketing capability to do so.</p><p>The pieces are assembling. The entrepreneurs are here. The ingredients are here. The question now is whether the ecosystem — investors, government support, export infrastructure — will come together quickly enough to let these brands realise their potential.</p>',
                    'published_at'   => now()->subDays(8),
                ],
                [
                    'title'          => 'From Sorghum Field to Pint Glass: Savanna\'s Farm-to-Tap Story',
                    'category'       => 'Sustainability',
                    'excerpt'        => 'How a Lusaka brewery built a fully Zambian supply chain — and what it means for the farmers who grow its ingredients.',
                    'featured_image' => $this->px(6190149),
                    'body'           => '<p>Most brewery supply chains are invisible to the consumer. Ingredients arrive in unmarked sacks, are transformed into beer, and the provenance is lost. At Savanna Brew Co, the supply chain is part of the product — documented, celebrated, and told to every customer who orders a pint.</p><p>The brewery\'s head brewer, Mwamba Chilufya, can tell you exactly where every ingredient in every beer comes from. The sorghum in the Savanna Lager was harvested by the Banda Family Cooperative in Chipata, Eastern Province, in April. The baobab in the seasonal wheat ale was collected from wild trees in Choma, Southern Province, by a women\'s cooperative that has been supplying the brewery since its second year. The honey in the winter stout comes from traditional beehives in the Kafue wetlands, managed by a third-generation beekeeper named Samuel.</p><p>"We know their names," Mwamba says simply. "We visit them. We know the conditions. That is not possible with an anonymous commodity supply chain, and I think it makes better beer."</p><p>The commitment to local sourcing began partly as an experiment — Chileshe Mwape wanted to see whether genuinely Zambian ingredients could produce beers with distinctive, marketable flavour profiles — and partly as a values-based decision to keep economic value within Zambia. The experiment succeeded beyond expectations. The Baobab Wheat Ale has become the brewery\'s most discussed product, with tasting notes that professional beer writers have described as "unlike anything produced outside Africa."</p><p>The impact on supplier communities has been significant. The Banda Cooperative has used revenue from their Savanna contract to purchase a grain storage facility, reducing post-harvest losses and improving the quality of their deliveries. Samuel the beekeeper has expanded from eight traditional hives to twenty-two, and is training his son in hive management. The women\'s cooperative in Choma has used their baobab income to fund school fees for eleven children.</p><p>"I am in the beer business," Chileshe says. "But I am also in the business of Zambian agriculture, Zambian communities, and Zambian stories. They are all the same business, really."</p>',
                    'published_at'   => now()->subDays(0),
                ],
            ],
        ];

        foreach ($posts as $brandName => $brandPosts) {
            $brand = Brand::where('name', $brandName)->first();
            if (! $brand) continue;

            foreach ($brandPosts as $postData) {
                $categoryId = $cat($postData['category']);
                $slug       = Str::slug($postData['title']);

                Post::updateOrCreate(
                    ['slug' => $slug],
                    [
                        'user_id'        => $admin->id,
                        'brand_id'       => $brand->id,
                        'category_id'    => $categoryId,
                        'title'          => $postData['title'],
                        'excerpt'        => $postData['excerpt'],
                        'body'           => $postData['body'],
                        'featured_image' => $postData['featured_image'],
                        'status'         => 'published',
                        'published_at'   => $postData['published_at'],
                    ]
                );
            }
        }
    }
}
